import { IPortfolioData } from '@/utils/types'

export const USER_DATA: IPortfolioData = {
  personal: {
    name: 'Henrique Garcia',
    title: {
      main: 'Desenvolvedor Full-Stack | Foco em Front-End',
      hero: ['Full-Stack', 'Front-End', 'E-commerce', 'Mobile', 'de Jogos', 'Back-End'],
    },
    email: 'henriquegarcia.tech@gmail.com',
    phone: '+55 84 99814-7860',
    whatsapp: 'https://wa.me/5584998147860',
    location: 'Natal, RN',
    summary:
      'Sou um profissional proativo e movido por desafios, com mais de cinco anos dedicados à construção de softwares. Tenho uma abordagem orientada à solução e o hábito de me aprofundar em novas tecnologias de forma autodidata. Em meu tempo livre, gosto de aplicar minhas habilidades em projetos variados, que vão desde a construção de sistemas e aplicativos complexos até o desenvolvimento de jogos.',
    heroSummary:
      'Crio soluções digitais que resolvem problemas reais e geram valor, da concepção à entrega final.',
    socialLinks: {
      github: 'https://github.com/henriquegarcia-web',
      linkedin: 'https://www.linkedin.com/in/henrique-garcia-dev',
      behance: 'https://www.behance.net/henrique-garcia-dev',
    },
    interests: ['Código Aberto', 'UX', 'Jogos 3D Realistas', 'IA', 'Metodologias Ágeis'],
  },

  technicalAreas: [
    {
      title: 'E-Commerce',
      icon: '💻',
      description:
        'Soluções de e-commerce com foco em performance, SEO, Checkout e Integrações',
    },
    {
      title: 'Sistemas de Gestão',
      icon: '⚙️',
      description:
        'Plataformas de Gestão Complexas, Sistemas Multi-Plataforma, Multi-Tenant e SaaS',
    },
    {
      title: 'Resolução de Problemas',
      icon: '💡',
      description:
        'Foco na resolução prática, usando princípios de arquitetura sólida para entregar resultados eficientes e de alta qualidade',
    },
  ],

  experience: [
    {
      id: 'moovin-2021',
      position: 'Desenvolvedor Front-End',
      company: 'Moovin E-commerce',
      location: 'Remoto',
      type: 'remote',
      startDate: '2021-02',
      endDate: '2021-10',
      description:
        'Atuei em um projeto de modernização de temas e componentes visuais para uma plataforma de e-commerce white-label, com mais de 1.000 lojas ativas na base.',
      achievements: [
        'Padronização de layouts e documentação de temas',
        'Suporte a customizações para clientes',
        'Contribuições para melhorias internas no design system',
        'Redução de tempo de entrega de novos templates',
        'Melhorias no desempenho visual dos clientes',
      ],
      technologies: [
        'HTML5',
        'CSS3',
        'JavaScript',
        'SASS',
        'jQuery',
        'Design System',
        'SEO Optimization',
        'Core Web Vitals',
        'Git',
      ],
    },
    {
      id: 'grupo-pereira-2022',
      position: 'Desenvolvedor Front-End Pleno',
      company: 'Grupo Pereira',
      location: 'Remoto',
      type: 'remote',
      startDate: '2022-09',
      endDate: '2023-04',
      description:
        'Fiz parte de um time responsável por uma plataforma de e-commerce de grande porte, com alta volumetria de acessos e foco em performance.',
      achievements: [
        'Manutenção de interfaces em plataforma de alto volume',
        'Migração de estruturas antigas para padrões modernos',
        'Colaboração direta com desenvolvedores, designers e times de produto',
        'Participação em entregas recorrentes em sprints',
        'Contribuições para refatorações e testes automatizados',
        'Melhoria da experiência do usuário',
      ],
      technologies: [
        'React',
        'Redux',
        'TypeScript',
        'GraphQL',
        'REST APIs',
        'React Native',
        'Magento',
        'Cypress',
        'RTL (React Testing Library)',
        'Jira',
        'Bitbucket',
        'Git',
      ],
    },
    {
      id: 'freelancer-2018',
      position: 'Freelancer Full-Stack',
      company: '99Freelas/Workana',
      location: 'Remoto',
      type: 'remote',
      startDate: '2018-01',
      endDate: 'present',
      current: true,
      description:
        'Atuei em mais de 20 projetos completos como desenvolvedor full-stack, com entregas que vão desde MVPs entregues em menos de 10 dias até plataformas robustas com estrutura modular e gestão de usuários.',
      achievements: [
        'Mais de 20 projetos completos desenvolvidos',
        'Sistemas utilizados por mais de 10 mil acessos mensais',
        'Responsável por todas as etapas: levantamento, planejamento, desenvolvimento, testes, deploy, manutenção',
        'Experiência com SaaS, plataformas administrativas, produtos digitais',
        'Integrações com meios de pagamento e sistemas de gestão',
        'Múltiplos fluxos simultâneos (administração, autenticação, checkout, conteúdo dinâmico)',
      ],
      technologies: [
        'React',
        'Next.js',
        'TypeScript',
        'Node.js',
        'Express',
        'Firebase (Auth, Firestore, Storage, Functions)',
        'PostgreSQL',
        'Prisma ORM',
        'Stripe API',
        'Tailwind CSS',
        'Styled Components',
        'React Query',
        'React Hook Form',
        'Yup',
        'Ant Design',
        'Context API',
        'JWT',
        'i18n',
        'Vite',
        'Git',
        'WebSockets',
        'ViaCEP API',
      ],
    },
  ],

  education: [
    {
      id: 'master-2019',
      degree: 'Ensino Médio Completo',
      institution: 'Colégio Master',
      location: 'João Pessoa, RN',
      startDate: '2019-03',
      endDate: '2022-10',
      current: false,
    },
    {
      id: 'senac-2018',
      degree: 'Curso Técnico de Programação de Jogos Digitais',
      institution: 'Senac RS',
      location: 'Porto Alegre, RS',
      startDate: '2018-01',
      endDate: '2019-12',
      current: false,
      description:
        'Curso com mais de 1.200 horas focado no desenvolvimento completo de jogos 2D e 3D.',
      projects: [
        'Mais de 10 projetos práticos durante a formação',
        'Jogo final autoral com sistema de fases, interface e mecânicas próprias',
        'Estudos em fundamentos de lógica, física aplicada, IA básica, narrativa interativa e organização de assets',
      ],
    },
    {
      id: 'jogos-2025',
      degree: 'Bacharelado EAD em Jogos Digitais',
      institution: 'UNP',
      location: 'Natal, RN',
      startDate: '2025-09',
      endDate: '2029-10',
      current: true,
    },
  ],

  certifications: [
    {
      id: 'scrum-master',
      name: 'Scrum Master',
      issuer: 'Udemy',
      date: '2023',
      description:
        'Formação voltada à aplicação prática do framework Scrum em projetos reais, com foco em gestão de sprints, definição de backlog, papéis do time ágil e entregas contínuas dentro de contextos de produto digital.',
    },
    {
      id: 'frontend-moderno',
      name: 'Front-End Moderno',
      issuer: 'Alura',
      date: '2023',
      description:
        'Capacitação em desenvolvimento com React, componentes reutilizáveis, hooks, controle de estado, rotas e consumo de APIs REST, abordando o ecossistema moderno do front-end com foco em experiência do usuário, responsividade e manutenção de código.',
    },
    {
      id: 'desenvolvimento-web-completo',
      name: 'Desenvolvimento Web Completo',
      issuer: 'Danki Code',
      date: '2022',
      description:
        'Formação intensiva abordando o ciclo completo de uma aplicação full-stack com React no front e Node.js no back, incluindo criação de APIs, autenticação, manipulação de dados, deploy, e aplicação prática de conceitos como responsividade, SPA e integração com banco de dados.',
    },
    {
      id: 'okr-agilidade',
      name: 'Formação OKR & Agilidade Profissional',
      issuer: 'G4 Educação',
      date: '2023',
      description:
        'Curso estratégico voltado à criação de metas organizacionais aplicadas ao desenvolvimento de software, com foco em produtividade, alinhamento de times de produto e tomada de decisão baseada em ciclos ágeis de planejamento e resultados chave (OKRs).',
    },
  ],

  skills: [
    {
      category: 'Front-End',
      technologies: [
        {
          name: 'React.js',
          iconKey: 'react',
          level: 'advanced',
          projects: 15,
          jobs: 2,
          courses: 3,
        },
        {
          name: 'Next.js',
          iconKey: 'nextjs',
          level: 'advanced',
          projects: 8,
          jobs: 1,
          courses: 2,
        },
        {
          name: 'TypeScript',
          iconKey: 'typescript',
          level: 'advanced',
          projects: 12,
          jobs: 2,
          courses: 2,
        },
        {
          name: 'JavaScript',
          iconKey: 'js',
          level: 'advanced',
          projects: 20,
          jobs: 3,
          courses: 4,
        },
        {
          name: 'Tailwind CSS',
          iconKey: 'tailwindcss',
          level: 'advanced',
          projects: 10,
          jobs: 2,
          courses: 1,
        },
        {
          name: 'Styled Components',
          iconKey: 'styledcomponents',
          level: 'intermediate',
          projects: 5,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Material UI',
          iconKey: 'materialui',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Redux',
          iconKey: 'redux',
          level: 'intermediate',
          projects: 4,
          jobs: 1,
          courses: 1,
        },
      ],
    },
    {
      category: 'Back-End',
      technologies: [
        {
          name: 'Node.js',
          iconKey: 'nodejs',
          level: 'advanced',
          projects: 12,
          jobs: 2,
          courses: 2,
        },
        {
          name: 'Express.js',
          iconKey: 'expressjs',
          level: 'advanced',
          projects: 8,
          jobs: 2,
          courses: 1,
        },
        {
          name: 'NestJS',
          iconKey: 'nestjs',
          level: 'intermediate',
          projects: 3,
          jobs: 0,
          courses: 1,
        },
        {
          name: 'Firebase Functions',
          iconKey: 'firebase',
          level: 'advanced',
          projects: 6,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Prisma ORM',
          iconKey: 'prisma',
          level: 'intermediate',
          projects: 4,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'GraphQL',
          iconKey: 'graphql',
          level: 'learning',
          projects: 1,
          jobs: 0,
          courses: 1,
        },
      ],
    },
    {
      category: 'Banco de Dados',
      technologies: [
        {
          name: 'PostgreSQL',
          iconKey: 'postgresql',
          level: 'advanced',
          projects: 8,
          jobs: 2,
          courses: 1,
        },
        {
          name: 'MongoDB',
          iconKey: 'mongodb',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Firebase Firestore',
          iconKey: 'firebase',
          level: 'advanced',
          projects: 6,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'MySQL',
          iconKey: 'mysql',
          level: 'intermediate',
          projects: 2,
          jobs: 1,
          courses: 1,
        },
      ],
    },
    {
      category: 'DevOps & Infraestrutura',
      technologies: [
        {
          name: 'Docker',
          iconKey: 'docker',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'AWS',
          iconKey: 'aws',
          level: 'learning',
          projects: 1,
          jobs: 0,
          courses: 1,
        },
        {
          name: 'Vercel',
          iconKey: 'vercel',
          level: 'advanced',
          projects: 10,
          jobs: 2,
          courses: 0,
        },
        {
          name: 'GitHub Actions',
          iconKey: 'github',
          level: 'intermediate',
          projects: 5,
          jobs: 1,
          courses: 0,
        },
      ],
    },
    {
      category: 'Testes',
      technologies: [
        {
          name: 'Jest',
          iconKey: 'jest',
          level: 'intermediate',
          projects: 4,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Cypress',
          iconKey: 'cypress',
          level: 'learning',
          projects: 2,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'React Testing Library',
          iconKey: 'react',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Vitest',
          iconKey: 'vitest',
          level: 'learning',
          projects: 1,
          jobs: 0,
          courses: 0,
        },
      ],
    },
    {
      category: 'Ferramentas & Outros',
      technologies: [
        {
          name: 'Git',
          iconKey: 'git',
          level: 'advanced',
          projects: 25,
          jobs: 3,
          courses: 1,
        },
        {
          name: 'Figma',
          iconKey: 'figma',
          level: 'intermediate',
          projects: 5,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Vite',
          iconKey: 'vitejs',
          level: 'advanced',
          projects: 8,
          jobs: 2,
          courses: 0,
        },
        {
          name: 'Postman',
          iconKey: 'postman',
          level: 'advanced',
          projects: 15,
          jobs: 3,
          courses: 1,
        },
        {
          name: 'Stripe API',
          iconKey: 'stripe',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 0,
        },
        {
          name: 'Webpack',
          iconKey: 'webpack',
          level: 'learning',
          projects: 2,
          jobs: 0,
          courses: 1,
        },
      ],
    },
  ],

  projects: [
    {
      id: 'ecommerce-platform',
      title: 'Plataforma E-commerce',
      description: 'Sistema completo de e-commerce com mais de 1.000 lojas ativas',
      technologies: ['React', 'TypeScript', 'Styled Components', 'Node.js', 'PostgreSQL'],
      features: [
        'Sistema de temas customizáveis',
        'Dashboard administrativo completo',
        'Integração com gateways de pagamento',
        'SEO otimizado',
        'Design system padronizado',
      ],
      images: [
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1556742111-a301076d9d18?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop',
      ],
      status: 'completed',
      featured: true,
      startDate: '2021-02',
      endDate: '2021-10',
    },
    {
      id: 'admin-dashboard',
      title: 'Dashboard Administrativo',
      description: 'Sistema de gestão com mais de 10 mil acessos mensais',
      technologies: [
        'Next.js',
        'TypeScript',
        'Tailwind CSS',
        'Prisma',
        'PostgreSQL',
        'Stripe',
      ],
      features: [
        'Autenticação JWT',
        'Gestão de usuários e permissões',
        'Relatórios em tempo real',
        'Integração com Stripe',
        'Interface responsiva',
      ],
      images: [
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
      ],
      status: 'completed',
      featured: true,
    },
    {
      id: 'mobile-app',
      title: 'Aplicativo Mobile React Native',
      description:
        'App mobile com funcionalidades avançadas e sincronização em tempo real',
      technologies: ['React Native', 'TypeScript', 'Redux', 'Firebase', 'WebSockets'],
      features: [
        'Funcionalidades offline',
        'Sincronização em tempo real',
        'Push notifications',
        'Integração com APIs REST',
        'Interface nativa',
      ],
      images: [
        'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop',
      ],
      status: 'completed',
      featured: true,
    },
  ],

  resumeUrl: '/resume-henrique-garcia.pdf',
}
