import { IPortfolioData } from '@/utils/types'

export const USER_DATA: IPortfolioData = {
  personal: {
    name: 'Henrique Garcia',
    title: {
      main: 'Desenvolvedor Full-Stack | Foco em Front-End',
      hero: ['Full-Stack', 'Front-End', 'E-commerce', 'Mobile', 'de Jogos', 'Back-End'],
    },
    email: 'henriquegarcia.tech@gmail.com',
    phone: '+55 84 99814-7860',
    whatsapp: 'https://wa.me/5584998147860',
    location: 'Natal, RN',
    summary:
      'Sou um profissional proativo e movido por desafios, com mais de cinco anos dedicados à construção de softwares. Tenho uma abordagem orientada à solução e o hábito de me aprofundar em novas tecnologias de forma autodidata. Em meu tempo livre, gosto de aplicar minhas habilidades em projetos variados, que vão desde a construção de sistemas e aplicativos complexos até o desenvolvimento de jogos.',
    heroSummary:
      'Crio soluções digitais que resolvem problemas reais e geram valor, da concepção à entrega final.',
    socialLinks: {
      github: 'https://github.com/henriquegarcia-web',
      linkedin: 'https://www.linkedin.com/in/henrique-garcia-dev',
      behance: 'https://www.behance.net/henrique-garcia-dev',
    },
    interests: ['Código Aberto', 'UX', 'Jogos 3D Realistas', 'IA', 'Metodologias Ágeis'],
  },

  technicalAreas: [
    {
      title: 'E-Commerce',
      icon: '💻',
      description:
        'Soluções de e-commerce com foco em performance, SEO, Checkout e Integrações',
    },
    {
      title: 'Sistemas de Gestão',
      icon: '⚙️',
      description:
        'Plataformas de Gestão Complexas, Sistemas Multi-Plataforma, Multi-Tenant e SaaS',
    },
    {
      title: 'Resolução de Problemas',
      icon: '💡',
      description:
        'Foco na resolução prática, usando princípios de arquitetura sólida para entregar resultados eficientes e de alta qualidade',
    },
  ],

  experience: [
    {
      id: 'moovin-2021',
      position: 'Desenvolvedor Front-End',
      company: 'Moovin E-commerce',
      location: 'Remoto',
      type: 'remote',
      startDate: '2021-02',
      endDate: '2021-10',
      description:
        'Atuei em um projeto de modernização de temas e componentes visuais para uma plataforma de e-commerce white-label, com mais de 1.000 lojas ativas na base.',
      achievements: [
        'Padronização de layouts e documentação de temas',
        'Suporte a customizações para clientes',
        'Contribuições para melhorias internas no design system',
        'Redução de tempo de entrega de novos templates',
        'Melhorias no desempenho visual dos clientes',
      ],
      technologies: [
        'HTML5',
        'CSS3',
        'JavaScript',
        'SASS',
        'jQuery',
        'Design System',
        'SEO Optimization',
        'Core Web Vitals',
        'Git',
      ],
    },
    {
      id: 'grupo-pereira-2022',
      position: 'Desenvolvedor Front-End Pleno',
      company: 'Grupo Pereira',
      location: 'Remoto',
      type: 'remote',
      startDate: '2022-09',
      endDate: '2023-04',
      description:
        'Fiz parte de um time responsável por uma plataforma de e-commerce de grande porte, com alta volumetria de acessos e foco em performance.',
      achievements: [
        'Manutenção de interfaces em plataforma de alto volume',
        'Migração de estruturas antigas para padrões modernos',
        'Colaboração direta com desenvolvedores, designers e times de produto',
        'Participação em entregas recorrentes em sprints',
        'Contribuições para refatorações e testes automatizados',
        'Melhoria da experiência do usuário',
      ],
      technologies: [
        'React',
        'Redux',
        'TypeScript',
        'GraphQL',
        'REST APIs',
        'React Native',
        'Magento',
        'Cypress',
        'RTL (React Testing Library)',
        'Jira',
        'Bitbucket',
        'Git',
      ],
    },
    {
      id: 'freelancer-2018',
      position: 'Freelancer Full-Stack',
      company: '99Freelas/Workana',
      location: 'Remoto',
      type: 'remote',
      startDate: '2018-01',
      endDate: 'present',
      current: true,
      description:
        'Atuei em mais de 20 projetos completos como desenvolvedor full-stack, com entregas que vão desde MVPs entregues em menos de 10 dias até plataformas robustas com estrutura modular e gestão de usuários.',
      achievements: [
        'Mais de 20 projetos completos desenvolvidos',
        'Sistemas utilizados por mais de 10 mil acessos mensais',
        'Responsável por todas as etapas: levantamento, planejamento, desenvolvimento, testes, deploy, manutenção',
        'Experiência com SaaS, plataformas administrativas, produtos digitais',
        'Integrações com meios de pagamento e sistemas de gestão',
        'Múltiplos fluxos simultâneos (administração, autenticação, checkout, conteúdo dinâmico)',
      ],
      technologies: [
        'React',
        'Next.js',
        'TypeScript',
        'Node.js',
        'Express',
        'Firebase (Auth, Firestore, Storage, Functions)',
        'PostgreSQL',
        'Prisma ORM',
        'Stripe API',
        'Tailwind CSS',
        'Styled Components',
        'React Query',
        'React Hook Form',
        'Yup',
        'Ant Design',
        'Context API',
        'JWT',
        'i18n',
        'Vite',
        'Git',
        'WebSockets',
        'ViaCEP API',
      ],
    },
  ],

  education: [
    {
      id: 'master-2019',
      degree: 'Ensino Médio Completo',
      institution: 'Colégio Master',
      location: 'João Pessoa, RN',
      startDate: '2019-03',
      endDate: '2022-10',
      current: false,
    },
    {
      id: 'senac-2018',
      degree: 'Curso Técnico de Programação de Jogos Digitais',
      institution: 'Senac RS',
      location: 'Porto Alegre, RS',
      startDate: '2018-01',
      endDate: '2019-12',
      current: false,
      description:
        'Curso com mais de 1.200 horas focado no desenvolvimento completo de jogos 2D e 3D.',
      projects: [
        'Mais de 10 projetos práticos durante a formação',
        'Jogo final autoral com sistema de fases, interface e mecânicas próprias',
        'Estudos em fundamentos de lógica, física aplicada, IA básica, narrativa interativa e organização de assets',
      ],
    },
    {
      id: 'jogos-2025',
      degree: 'Bacharelado EAD em Jogos Digitais',
      institution: 'UNP',
      location: 'Natal, RN',
      startDate: '2025-09',
      endDate: '2029-10',
      current: true,
    },
  ],

  certifications: [
    {
      id: 'scrum-master',
      name: 'Scrum Master',
      issuer: 'Udemy',
      date: '2023',
      description:
        'Formação voltada à aplicação prática do framework Scrum em projetos reais, com foco em gestão de sprints, definição de backlog, papéis do time ágil e entregas contínuas dentro de contextos de produto digital.',
    },
    {
      id: 'frontend-moderno',
      name: 'Front-End Moderno',
      issuer: 'Alura',
      date: '2023',
      description:
        'Capacitação em desenvolvimento com React, componentes reutilizáveis, hooks, controle de estado, rotas e consumo de APIs REST, abordando o ecossistema moderno do front-end com foco em experiência do usuário, responsividade e manutenção de código.',
    },
    {
      id: 'desenvolvimento-web-completo',
      name: 'Desenvolvimento Web Completo',
      issuer: 'Danki Code',
      date: '2022',
      description:
        'Formação intensiva abordando o ciclo completo de uma aplicação full-stack com React no front e Node.js no back, incluindo criação de APIs, autenticação, manipulação de dados, deploy, e aplicação prática de conceitos como responsividade, SPA e integração com banco de dados.',
    },
    {
      id: 'okr-agilidade',
      name: 'Formação OKR & Agilidade Profissional',
      issuer: 'G4 Educação',
      date: '2023',
      description:
        'Curso estratégico voltado à criação de metas organizacionais aplicadas ao desenvolvimento de software, com foco em produtividade, alinhamento de times de produto e tomada de decisão baseada em ciclos ágeis de planejamento e resultados chave (OKRs).',
    },
  ],

  skills: [
    {
      category: 'Front-End',
      technologies: [
        {
          name: 'React.js',
          iconKey: 'react',
          level: 'advanced',
          projects: 15,
          jobs: 2,
          courses: 3,
        },
        {
          name: 'Next.js',
          iconKey: 'nextjs',
          level: 'advanced',
          projects: 8,
          jobs: 1,
          courses: 2,
        },
        {
          name: 'TypeScript',
          iconKey: 'typescript',
          level: 'advanced',
          projects: 12,
          jobs: 2,
          courses: 2,
        },
        {
          name: 'JavaScript',
          iconKey: 'js',
          level: 'advanced',
          projects: 20,
          jobs: 3,
          courses: 4,
        },
        {
          name: 'Tailwind CSS',
          iconKey: 'tailwindcss',
          level: 'advanced',
          projects: 10,
          jobs: 2,
          courses: 1,
        },
        {
          name: 'Styled Components',
          iconKey: 'styledcomponents',
          level: 'intermediate',
          projects: 5,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Material UI',
          iconKey: 'materialui',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Redux',
          iconKey: 'redux',
          level: 'intermediate',
          projects: 4,
          jobs: 1,
          courses: 1,
        },
      ],
    },
    {
      category: 'Back-End',
      technologies: [
        {
          name: 'Node.js',
          iconKey: 'nodejs',
          level: 'advanced',
          projects: 12,
          jobs: 2,
          courses: 2,
        },
        {
          name: 'Express.js',
          iconKey: 'expressjs',
          level: 'advanced',
          projects: 8,
          jobs: 2,
          courses: 1,
        },
        {
          name: 'NestJS',
          iconKey: 'nestjs',
          level: 'intermediate',
          projects: 3,
          jobs: 0,
          courses: 1,
        },
        {
          name: 'Firebase Functions',
          iconKey: 'firebase',
          level: 'advanced',
          projects: 6,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Prisma ORM',
          iconKey: 'prisma',
          level: 'intermediate',
          projects: 4,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'GraphQL',
          iconKey: 'graphql',
          level: 'learning',
          projects: 1,
          jobs: 0,
          courses: 1,
        },
      ],
    },
    {
      category: 'Banco de Dados',
      technologies: [
        {
          name: 'PostgreSQL',
          iconKey: 'postgresql',
          level: 'advanced',
          projects: 8,
          jobs: 2,
          courses: 1,
        },
        {
          name: 'MongoDB',
          iconKey: 'mongodb',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Firebase Firestore',
          iconKey: 'firebase',
          level: 'advanced',
          projects: 6,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'MySQL',
          iconKey: 'mysql',
          level: 'intermediate',
          projects: 2,
          jobs: 1,
          courses: 1,
        },
      ],
    },
    {
      category: 'DevOps & Infraestrutura',
      technologies: [
        {
          name: 'Docker',
          iconKey: 'docker',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'AWS',
          iconKey: 'aws',
          level: 'learning',
          projects: 1,
          jobs: 0,
          courses: 1,
        },
        {
          name: 'Vercel',
          iconKey: 'vercel',
          level: 'advanced',
          projects: 10,
          jobs: 2,
          courses: 0,
        },
        {
          name: 'GitHub Actions',
          iconKey: 'github',
          level: 'intermediate',
          projects: 5,
          jobs: 1,
          courses: 0,
        },
      ],
    },
    {
      category: 'Testes',
      technologies: [
        {
          name: 'Jest',
          iconKey: 'jest',
          level: 'intermediate',
          projects: 4,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Cypress',
          iconKey: 'cypress',
          level: 'learning',
          projects: 2,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'React Testing Library',
          iconKey: 'react',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Vitest',
          iconKey: 'vitest',
          level: 'learning',
          projects: 1,
          jobs: 0,
          courses: 0,
        },
      ],
    },
    {
      category: 'Ferramentas & Outros',
      technologies: [
        {
          name: 'Git',
          iconKey: 'git',
          level: 'advanced',
          projects: 25,
          jobs: 3,
          courses: 1,
        },
        {
          name: 'Figma',
          iconKey: 'figma',
          level: 'intermediate',
          projects: 5,
          jobs: 1,
          courses: 1,
        },
        {
          name: 'Vite',
          iconKey: 'vitejs',
          level: 'advanced',
          projects: 8,
          jobs: 2,
          courses: 0,
        },
        {
          name: 'Postman',
          iconKey: 'postman',
          level: 'advanced',
          projects: 15,
          jobs: 3,
          courses: 1,
        },
        {
          name: 'Stripe API',
          iconKey: 'stripe',
          level: 'intermediate',
          projects: 3,
          jobs: 1,
          courses: 0,
        },
        {
          name: 'Webpack',
          iconKey: 'webpack',
          level: 'learning',
          projects: 2,
          jobs: 0,
          courses: 1,
        },
      ],
    },
  ],

  projects: [
    {
      id: 'uniw',
      title: 'E-commerce Multiplataforma',
      description:
        'Plataforma de e-commerce multi-tenant que conecta vendedores, clientes e fornecedores, com controle total para o administrador.',
      technologies: [
        'React',
        'Next.js',
        'TypeScript',
        'Node.js',
        'PostgreSQL',
        'Styled Components',
        'Prisma',
      ],
      features: [
        'Arquitetura multi-tenant escalável',
        'Dashboard administrativo e fornecedor',
        'Integração com gateways de pagamento',
        'Gestão de usuários e permissões',
        'SEO otimizado',
      ],
      images: [
        '/projects/1/1.png',
        '/projects/1/2.png',
        '/projects/1/3.png',
        '/projects/1/4.png',
        '/projects/1/5.png',
        '/projects/1/6.png',
      ],
      status: 'completed',
      featured: true,
      startDate: '2024-01',
      endDate: '2024-08',
    },
    {
      id: 'mandato-digital',
      title: 'Sistema de Gestão Política',
      description:
        'Plataforma para gestão política que otimiza o controle de eleitores, comunicação e atividades de campanha.',
      technologies: [
        'React',
        'Next.js',
        'TypeScript',
        'Node.js',
        'MongoDB',
        'Tailwind CSS',
      ],
      features: [
        'Gerenciamento de base de eleitores',
        'Automação de comunicação',
        'Análise de dados de campanha',
        'Sistema de relatórios em tempo real',
      ],
      images: ['/projects/2/1.png', '/projects/2/2.png'],
      status: 'completed',
      featured: true,
      startDate: '2023-10',
      endDate: '2024-03',
    },
    {
      id: 'hungry-hub',
      title: 'Sistema de Cardápio Online',
      description:
        'Plataforma online para gerenciamento de cardápios de restaurantes, permitindo atualização em tempo real e pedidos online.',
      technologies: ['React', 'JavaScript', 'Node.js', 'MongoDB', 'Redux', 'Material UI'],
      features: [
        'Painel administrativo intuitivo',
        'Interface de cardápio personalizável',
        'Gestão de pedidos e estoque',
        'Integração com sistemas de PDV',
      ],
      images: [
        '/projects/4/1.png',
        '/projects/4/2.png',
        '/projects/4/3.png',
        '/projects/4/4.png',
        '/projects/4/5.png',
        '/projects/4/6.png',
      ],
      status: 'completed',
      featured: true,
      startDate: '2024-02',
      endDate: '2024-07',
    },
    {
      id: 'quick-shop',
      title: 'E-commerce de Camisetas',
      description:
        'E-commerce moderno e dinâmico focado na venda de camisetas, com design clean e processo de compra otimizado.',
      technologies: [
        'React',
        'Next.js',
        'TypeScript',
        'Node.js',
        'Stripe API',
        'Tailwind CSS',
      ],
      features: [
        'Catálogo de produtos interativo',
        'Carrinho de compras intuitivo',
        'Integração de pagamento com Stripe',
        'Design responsivo',
      ],
      images: [
        '/projects/5/1.png',
        '/projects/5/2.png',
        '/projects/5/3.png',
        '/projects/5/4.png',
        '/projects/5/5.png',
        '/projects/5/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-04',
      endDate: '2024-06',
    },
    {
      id: 'agencia-bmw',
      title: 'Website Institucional BMW',
      description:
        'Website institucional para a Agência BMW, com design sofisticado e focado na experiência do usuário para apresentação de serviços e portfólio.',
      technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
      features: [
        'Design responsivo e elegante',
        'Galeria de projetos interativa',
        'Formulário de contato',
        'Otimização para SEO',
      ],
      images: [
        '/projects/6/1.png',
        '/projects/6/2.png',
        '/projects/6/3.png',
        '/projects/6/4.png',
        '/projects/6/5.png',
        '/projects/6/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2023-11',
      endDate: '2024-01',
    },
    {
      id: 'aplicativo-uniw',
      title: 'Aplicativo E-Commerce',
      description:
        'Aplicativo móvel que expande o e-commerce UNIWI, com funcionalidades completas na palma da mão para clientes e vendedores.',
      technologies: ['React Native', 'TypeScript', 'Redux', 'Firebase', 'WebSockets'],
      features: [
        'Sincronização em tempo real',
        'Notificações push',
        'Funcionalidades offline',
        'Integração com APIs REST',
      ],
      images: [
        '/projects/7/1.png',
        '/projects/7/2.png',
        '/projects/7/3.png',
        '/projects/7/4.png',
        '/projects/7/5.png',
        '/projects/7/6.png',
      ],
      status: 'completed',
      featured: true,
      startDate: '2024-05',
      endDate: '2024-09',
    },
    {
      id: 'portfolio-pessoal',
      title: 'Portfólio Pessoal',
      description:
        'Portfólio online para exposição de projetos e habilidades, funcionando como um cartão de visitas digital interativo e profissional.',
      technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
      features: [
        'Design minimalista e responsivo',
        'Seção de projetos detalhada',
        'Integração com redes sociais',
        'Otimização para performance',
      ],
      images: [
        '/projects/8/1.png',
        '/projects/8/2.png',
        '/projects/8/3.png',
        '/projects/8/4.png',
        '/projects/8/5.png',
        '/projects/8/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-07',
      endDate: '2024-08',
    },
    {
      id: 'rifas',
      title: 'Sistema de Rifas Online',
      description:
        'Plataforma de rifas online que permite a criação, gestão e participação em sorteios de forma segura e transparente.',
      technologies: [
        'React',
        'Next.js',
        'TypeScript',
        'Node.js',
        'PostgreSQL',
        'Styled Components',
      ],
      features: [
        'Sistema de geração de números',
        'Painel administrativo para controle total',
        'Integração com gateways de pagamento',
        'Notificações automáticas',
      ],
      images: [
        '/projects/9/1.png',
        '/projects/9/2.png',
        '/projects/9/3.png',
        '/projects/9/4.png',
        '/projects/9/5.png',
        '/projects/9/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-03',
      endDate: '2024-06',
    },
    {
      id: 'website-bmw',
      title: 'Website BMW',
      description:
        'Website premium para a BMW, focado em uma experiência de usuário de alta qualidade, apresentando a história e a linha de veículos da marca.',
      technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
      features: [
        'Design elegante e responsivo',
        'Animações e transições fluidas',
        'Galeria de modelos',
        'Formulários para agendamento',
      ],
      images: [
        '/projects/10/1.png',
        '/projects/10/2.png',
        '/projects/10/3.png',
        '/projects/10/4.png',
        '/projects/10/5.png',
        '/projects/10/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2023-11',
      endDate: '2024-01',
    },
    {
      id: 'agencia-marketing',
      title: 'Website de Agência',
      description:
        'Website institucional moderno e dinâmico para uma agência de marketing, com foco na apresentação de serviços e portfólio de sucesso.',
      technologies: ['React', 'Next.js', 'TypeScript', 'Node.js', 'Styled Components'],
      features: [
        'Layout modular e adaptável',
        'Sessão de portfólio interativa',
        'Blog integrado',
        'Formulário de contato e orçamento',
      ],
      images: [
        '/projects/11/1.png',
        '/projects/11/2.png',
        '/projects/11/3.png',
        '/projects/11/4.png',
        '/projects/11/5.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-02',
      endDate: '2024-04',
    },
    {
      id: 'site-fit',
      title: 'Website Fitness',
      description:
        'Website para o nicho de fitness, com funcionalidades de agendamento de aulas, planos e conteúdos sobre bem-estar e saúde.',
      technologies: ['React', 'JavaScript', 'Node.js', 'Express.js', 'MongoDB'],
      features: [
        'Sistema de agendamento online',
        'Seção de blog e notícias',
        'Área do aluno e painel de controle',
        'Integração com redes sociais',
      ],
      images: [
        '/projects/12/1.png',
        '/projects/12/2.png',
        '/projects/12/3.png',
        '/projects/12/4.png',
        '/projects/12/5.png',
        '/projects/12/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2023-09',
      endDate: '2023-11',
    },
    {
      id: 'sistema-delivery',
      title: 'Sistema de Delivery',
      description:
        'Plataforma completa para gestão de delivery, com painel para restaurantes e interface para clientes, otimizando o processo de pedidos e entregas.',
      technologies: ['React', 'JavaScript', 'Node.js', 'Express.js', 'PostgreSQL'],
      features: [
        'Painel de pedidos em tempo real',
        'Gestão de cardápio e promoções',
        'Rastreamento de entregas',
        'Sistema de avaliações',
      ],
      images: [
        '/projects/13/1.png',
        '/projects/13/2.png',
        '/projects/13/3.png',
        '/projects/13/4.png',
        '/projects/13/5.png',
        '/projects/13/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-01',
      endDate: '2024-03',
    },
    {
      id: 'sistema-atendimento',
      title: 'CRM para Freelancers',
      description:
        'Sistema de atendimento que organiza e centraliza as interações com os clientes, otimizando a comunicação e a resolução de problemas.',
      technologies: ['React', 'TypeScript', 'Node.js', 'Express.js', 'PostgreSQL'],
      features: [
        'Chat em tempo real',
        'Histórico de conversas',
        'Dashboard de métricas de atendimento',
        'Sistema de fila e priorização',
      ],
      images: [
        '/projects/15/1.png',
        '/projects/15/2.png',
        '/projects/15/3.png',
        '/projects/15/4.png',
        '/projects/15/5.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-03',
      endDate: '2024-05',
    },
    {
      id: 'sistema-tickets',
      title: 'Sistema de Tickets',
      description:
        'Plataforma para gerenciamento de tickets de suporte, que organiza e atribui solicitações, garantindo um fluxo de trabalho eficiente para a equipe.',
      technologies: ['React', 'TypeScript', 'Node.js', 'Prisma', 'PostgreSQL'],
      features: [
        'Criação e rastreamento de tickets',
        'Atribuição automática ou manual',
        'Relatórios de desempenho',
        'Notificações de status',
      ],
      images: [
        '/projects/14/1.png',
        '/projects/14/2.png',
        '/projects/14/3.png',
        '/projects/14/4.png',
        '/projects/14/5.png',
        '/projects/14/6.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-04',
      endDate: '2024-07',
    },
    {
      id: 'landing-page-ebook',
      title: 'Landing Page E-book',
      description:
        'Landing page otimizada para alta conversão, com o objetivo de promover e capturar leads através do download de um e-book.',
      technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
      features: [
        'Formulário de captura de leads',
        'Design atraente e focado em conversão',
        'Otimização de SEO',
        'Integração com ferramentas de e-mail marketing',
      ],
      images: [
        '/projects/3/1.png',
        '/projects/3/2.png',
        '/projects/3/3.png',
        '/projects/3/4.png',
        '/projects/3/5.png',
        '/projects/3/6.png',
        '/projects/3/7.png',
      ],
      status: 'completed',
      featured: false,
      startDate: '2024-07',
      endDate: '2024-07',
    },
  ],

  resumeUrl: '/resume-henrique-garcia.pdf',
}
